@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

Package Controller
Package Util
Package Algorithm
Package Model
Package Test
Package View
Package Observer

View <-> Controller
Controller -> Model
View -> Model
Algorithm <- Controller
Controller -> Util

Util -> Test
Algorithm -> Test
View -> Observer

@enduml