@startuml

hide members
left to right direction
Package Controller{
    class Controller

    interface Command
    class InitialState
    class CalculateState
    class MapLoadedState
    class RequestLoadedState

    interface State
    Controller --> State
    InitialState ..|> State
    CalculateState ..|> State
    MapLoadedState ..|> State
    RequestLoadedState ..|> State
}
Package Util{
    class XMLParser
    class XMLfileOpener
    class ExceptionXML

    XMLParser --> XMLfileOpener

}
Package Algorithm{
    interface TSP
    class TSP1
    class TemplateTSP
    interface Graph
    class CompleteGraph
    class MapGraph
    class Seqlter



    TemplateTSP -> MapGraph
    Controller -up-> TSP
    TSP1 --|> TemplateTSP
    TemplateTSP ..|> TSP
    CompleteGraph..|> Graph

}
Package Model{
    class Intersection
    class Map
    class Mission
    class Request
    class Segment
    class Observable

    CompleteGraph --|> Mission
    CompleteGraph --|> Map
    Mission --|> Observable

    Map --> Intersection
    Map --> Segment
    Controller --> Map

    Controller --> Mission
    Mission --> Intersection
    Mission --> Request

    Request --> Intersection
    Segment --> Intersection

}
Package Test{
    class MapGraphTest
    class XMLparserTest

    XMLparserTest --> XMLParser
}
Package View{
    class Window
    class TextualView
    class GraphicalView
    class ButtonListener
    class MouseListener
    interface Observer

    TextualView ..|> Observer
    GraphicalView ..|> Observer

    Controller --> Window
    Window --> TextualView
    Window --> GraphicalView
    Window --> ButtonListener
    Window --> MouseListener

    TextualView --> Mission

    GraphicalView --> Map
    GraphicalView --> Mission
    GraphicalView --> TSP

    ButtonListener --> Controller

}




@enduml