@startuml
hide empty description

[*] -down-> InitialState
InitialState -down-> LoadStates
'InitialState : entry / requestListChanged = true

state CancelMapSelection
CancelMapSelection : do / backToPreviousState()


state CancelRequestSelection
CancelRequestSelection : do / backToPreviousState()

state LoadStates {
    [*] -down-> CancelMapSelection
    [*] -down-> MapLoadedState : loadMap()/\n resetAll() \n displayMap()
'    MapState1 : entry / isLoaded = isLoaded()

    MapLoadedState -down-> RequestLoadedState : loadRequests()/ \n clearPreviousRequests() \n displayRequests()
    MapLoadedState -up-> CancelRequestSelection : cancel()
}

'CancelMap -up-> InitialState : [ !isLoaded ]
'CancelMap -left-> MapState2 : [ isLoaded ]

RequestLoadedState -down-> OperationalStates : calculateTour() / displayTour()

OperationalStates -up-> LoadStates : loadMap() / clearMap()
OperationalStates -up-> MapLoadedState : loadRequests()
state OperationalStates {
    [*] -down-> CalculateState

    CalculateState: \n the State to which every operation \n undoable will finally come back \n
    CalculateState -down-> AddRequestState1 : addRequest()
    AddRequestState1 -down-> AddRequestState2 : leftClick(startPoint)
    AddRequestState2 -down-> AddRequestState3 : leftClick(pickupPoint)
    AddRequestState3 -down-> AddRequestState4 : leftClick(deliveryPoint)
    AddRequestState4 -down-> AddRequestState5 : leftClick(endPoint)
    AddRequestState5 : entry / popupWindow() \n do / fillRequestInfo()
    AddRequestState5 -left-> CalculateState : validate() / \n requestList.add(request) \n recalculateTour()
    AddRequestState1 -up-> CalculateState : rightClick()
    AddRequestState2 -up-> AddRequestState1 : rightClick()
    AddRequestState3 -up-> AddRequestState2 : rightClick()
    AddRequestState4 -up-> AddRequestState3 : rightClick()
    AddRequestState5 -left-> CalculateState : cancel()

    CalculateState -down-> DeleteState1 : deleteRequest()
    DeleteState1 : do / selectRequest()
    DeleteState1 -up-> CalculateState : deleteSelectedRequest() / \n requestList.remove(selectedRequest)

    CalculateState -left-> CalculateState : generateRoadMap()
    CalculateState -right-> CalculateState : undo() / \n undoLastCommand()
    CalculateState -right-> CalculateState : redo() / \n redoLastCommand()
}
@enduml