@startuml
'scale 350 width
'[*] --> NotShooting
'
'state NotShooting {
'  [*] --> Idle
'  Idle --> Configuring : EvConfig
'  Configuring --> Idle : EvConfig
'}
'
'state Configuring {
'  [*] --> NewValueSelection
'  NewValueSelection --> NewValuePreview : EvNewValue
'  NewValuePreview --> NewValueSelection : EvNewValueRejected
'  NewValuePreview --> NewValueSelection : EvNewValueSaved
'
'  state NewValuePreview {
'     State1 -> State2
'  }
'
'}


'For IHM'

[*] -> initialState
State initialState{

}

'loadMapState

initialState -down-> loadMapState : loadMap()
loadMapState -up-> initialState : doubleLeftClick()
loadMapState -up-> initialState : rightClick()

State loadMapState{
    loadMapState:entry/xml = new XMLFileOpener();
}

'loadRequestState

initialState -up-> loadRequestState : loadRequest()
loadRequestState -> initialState : doubleLeftClick()
loadRequestState -> initialState : rightClick()


State loadRequestState{
    loadRequestState:entry/xml = new XMLFileOpener();
}

'confirmRouteState
initialState -left-> confirmRouteState : confirmRoute()
confirmRouteState -down-> initialState

State confirmRouteState{
    '创建一个class用于执行确定route 但是不清楚class的名称
     confirmRouteState:entry/conf = new confirmation();
}

'calculateRouteState

initialState -> calculateRouteState : calculateRoute()
calculateRouteState -down-> initialState

State calculateRouteState{
    '创建一个class来计算 但是不清楚class的名称
    calculateRouteState:entry/ia = new iaCalculation();
}
@enduml