
@startuml


left to right direction

:Manager of Delivery: as User
:File System: as fs

package Application {
    usecase "Select Map" as UC1
    usecase "Load map" as UC2
    usecase "Load list of requests" as UC3
    usecase "Calculate route" as UC4
    usecase "Validate route" as UC5
    usecase "Add request" as UC6
    usecase "Change order of requests" as UC7
    usecase "Delete request" as UC8
    usecase "Produce route map" as UC9

    User -[hidden]->Application
    User ---> UC1
    User --> UC4
    User --> UC5
    User --> UC6
    User --> UC7
    User --> UC8
    Application -[hidden]> fs
    fs -> UC2
    fs -> UC3
    fs -> UC6
    fs -> UC8
    UC5 ..>UC9 : include
}

'note left of UC1
'the very first step
'of using the application
'end note

'note "This note is connected\nto several objects." as N2
'(Start) .. N2
'N2 .. (Use)

@enduml