
@startuml


left to right direction

:Manager of Delivery: as User
:File System: as fs

package Application {
    usecase "Load map" as LoadMap
    usecase "Load list of request" as LoadRequests
    usecase "Calculate Tour" as CalculateTour
    usecase "Generate RoadMap" as GenerateRoadMap
    usecase "Verify Route" as VerifyRoute
    usecase "Add Request" as AddRequest
    usecase "Delete Request" as DeleteRequest

    usecase "Parse XML file" as ParseXML
    usecase "Create and write txt file" as WriteTXT

    LoadMap ..> ParseXML : include
    LoadRequests ..> ParseXML : include
    GenerateRoadMap ..> WriteTXT : include
    GenerateRoadMap ..> VerifyRoute : include

    AddRequest ..> CalculateTour : extend
    DeleteRequest ..> CalculateTour : extend
}
    User -[hidden]->Application
    User --> LoadMap
    User --> LoadRequests
    User --> CalculateTour
    User --> GenerateRoadMap
    User --> AddRequest
    User --> DeleteRequest


'    Application -[hidden]> fs
    ParseXML -> fs
    WriteTXT -> fs


note right of CalculateTour
the Use Case Calculate Tour
is automatically invoked whenever
the user delete or add a request
end note

note top of LoadMap
the very first step of the
utilisation of the application,
and can be called in whichever step
end note

@enduml